const main = () => {
    // game object containing conversation data and methods
    const game = {
        _conversationData: {
            _greeting: [
                    'Hello', 'Hi', 'hey', 'good morning', 'it\'s nice to meet you',
                    'It\'s a pleasure to meet you', 'it\'s good to see you again', 'what\'s up', 'sup', 'how\'s it going?', 'how are you?', 'how have you been?', 'what\'s new'
            ],
            _continuation: [
                'That is cool!', 'Thanks for sharing', 'sounds good', 'really love it', 'nice to hear it', 'what a wonderful thing you\'ve told me', 'how astonishing', 'Oh really?', 'well, it is none of my buisiness I guess', 'wow, i like it', 'how good of you', 
            ],
            _fact: [
                "1. Three presidents, all Founding Fathers—John Adams, Thomas Jefferson, and James Monroe—died on July 4. Presidents Adams and Jefferson also died the same year, 1826; President Monroe died in 1831. Coincidence? You decide. (constitutioncenter.org)",
                "2. The Barbie doll’s full name is Barbara Millicent Roberts, from Willows, Wisconsin. Her birthday is March 9, 1959, when she was first displayed at the New York Toy Fair. (barbiemedia.com)",
                "3. There actually aren’t “57 varieties” of Heinz ketchup, and never were. Company founder H.J. Heinz thought his product should have a number, and he liked 57. Hint: Hit the glass bottle on the “57,” not the bottom, to get the ketchup to flow. (heinz.com)",
                "4. One of President John Tyler’s grandsons is still alive today—and he was born in 1790. How is this possible? President Tyler, the 10th US president, was 63 when his son Lyon Tyler was born in 1853; Lyon’s son was born when he was 75. President Tyler’s living grandson, Harrison Tyler is 92. Lyon’s other son Lyon Jr. passed away in 2020 at the age of 95. The Tyler family still maintains the President’s home, Sherwood Forest Plantation in Virginia. (sherwoodforest.org)",
                "5. The tallest man ever recorded was American giant Robert Wadlow (1918–1940), who stood 8 feet 11 inches. Wadlow’s size was the result of abnormally enlarged pituitary gland. (guinnessworldrecords.com)",
                "6. The tallest living man is 37-year-old Sultan Kosen, from Turkey, who is 8 feet, 2.8 inches, who set the record in 2009. His growth is also due to a pituitary issue. (guinnessworldrecords.com)",
                "7. The oldest person ever to have lived (whose age could be authenticated), a French woman named Jeanne Louise Calment, was 122 years old when she died in 1997. (guinnessworldrecord.com)",
                "8. Sliced bread was first manufactured by machine and sold in the 1920s by the Chillicothe Baking Company in Missouri. It was the greatest thing since…unsliced bread? (chllicothenews.com)",
                "9. The Earl of Sandwich, John Montagu, who lived in the 1700s, reportedly invented the sandwich so he wouldn’t have to leave his gambling table to eat. (pbs.org)",
                "10. The first college football game was played on November 6, 1869, between Rutgers and Princeton (then known as the College of New Jersey) in New Brunswick, New Jersey. Rutgers won. (ncaa.com)",
                "11. Experiments in universities have actually been carried out to figure out how many licks it takes to get to the center of a Tootsie Pop, both with machine and human lickers (because this is important scientific knowledge!). The results ranged from 252 to 411. (tootsie.com)",
                "12. The Four Corners is the only spot in the US where you can stand in four states at once: Utah, Colorado, Arizona and New Mexico. ",
                "13. Canada is south of Detroit (just look at a map).",
                "14. The original name for the search engine Google was Backrub. It was renamed Google after the googol, which is the number one followed by 100 zeros. (about.google)",
                "15. The oldest-known living land animal is a tortoise named Jonathan, who is 187 years old. He was born in 1832 and has lived on the island of St. Helena in the Atlantic Ocean since 1882. (guinnessworldrecords.com)",
                "16. Bats are the only mammal that can actually fly.",
                "17. Wombats are the only animal whose poop is cube-shaped. This is due to how its intestines form the feces. The animals then stack the cubes to mark their territory. (bbc.com)",
                "18. The most common wild bird in the world isn’t the sparrow or blue jay—it’s the red-billed quelea, which live in Africa and have an estimated population of 1.5 billion. (audubon.org)",
                "19. The heart of the blue whale, the largest animal on earth, is five feet long and weighs 400 pounds. The whale in total weighs 40,000 pounds. (nationalgeographic.com)",
                "20. For comparison, an elephant’s heart weighs around 30 pounds. And a human heart? A mere 10 ounces.",
                "21. Elephants can’t jump. (smithsonianmag.com)",
                "22. Octopuses have three hearts.",
                "23. Cows don’t actually have four stomachs; they have one stomach with four compartments. (fda.gov)",
                "24. The platypus doesn’t have a stomach at all: Their esophagus goes straight to their intestines. (nationalgeographic.com)",
                "25. This is one animal myth that’s true: Eating parts of a pufferfish can kill you because, in a defense mechanism to ward off predators, it contains a deadly chemical called tetrodotoxin. There’s enough in one pufferfish to kill 30 people—and there’s no antidote. Still, pufferfish, called fugu, is a highly-prized delicacy in Japan, but can only be prepared by well-trained chefs. (nationalgeographic.com)",
                "26. Polar bears have black skin. And actually, their fur isn’t white—it’s see-through, so it appears white as it reflects light.",
                "27. Tigers’ skin is actually striped, just like their fur. Also, no two fur patterns are alike.",
                "28. Flamingoes are only pink because of chemicals called carotenoids in the algae and fish (which also eat the algae) they eat; their feathers are grayish white when they’re born.",
                "29. Mosquitoes are the deadliest animal in the world: They kill more people than any other creature, due to the diseases they carry. (cdc.gov)",
                "30. What do Miss Piggy and Yoda have in common? They were both voiced by the same person, puppeteer Frank Oz.",
                "31. Psycho was the first movie to show a toilet flushing. (npr.com)",
                "32. One of the most famous movie lines in history was never said. We often quote, “Play it again, Sam,” from Casablanca; but the real line is, “Play it, Sam. Play ‘As Time Goes By.’” ",
                "33. The green code in The Matrix was actually created from symbols in the code designer’s wife’s sushi cookbook. (cnet.com)",
                "34. The wedding of Princess Diana and Prince Charles was watched by 750 million people worldwide in 1981; sadly, 2.5 billion watched her funeral in 1997. (bbc.com)",
                "35. With 3.572 billion viewers, half the world’s population watched the 2018 FIFA World Cup of soccer (or football, as many international fans call it), which is held every four years. That number is on par with the 2016 Summer Olympics; but only a quarter of the world watched the less-popular Winter Olympics in 2018. (fifa.com)",
                "36. There are no muscles in your fingers: Their function is controlled by muscles in your palms and arms. (assh.org)",
                "37. The hardest working muscle in your body is your heart: It pumps more than 2,000 gallons of blood a day and beats more than 2.5 billion times in a 70-year life span. (heart.org)",
                "38. It’s impossible to hum while holding your nose (just try it!).",
                "39. Skin is the body’s largest organ.",
                "40. The earth’s circumference is 24,900 miles. (nasa.gov)",
                "41. All of an adult human’s blood vessels, if laid out end to end, would be about 100,000 miles, so they could encircle the earth four times. (fi.edu)",
                "42. According to recent research, the human nose can distinguish at least a trillion different odors. (nature.com)",
                "43. The longest fingernails ever were over 28 feet in total. American Lee Redmond started growing them in 1979 and set the record in 2008. Sadly, she lost her nails in a car crash in 2009. (guinnessworldrecords.com)",
                "44. The origin of the word “sinister” reflects a historical bias against left-handed people. It comes from the Latin word for “left,” which was also seen to be unlucky or evil. (merriam-webster.com) ",
                "45. There is not one letter “q” in any US state name, the only letter in the alphabet to be missing. “J” and “z” are only represented once each, in New Jersey and Arizona.",
                "46. The word “strengths” is the longest word in the English language with only one vowel. (guinnessworldrecords.com)",
                "47. Cartoonist Mort Walker, creator of Beetle Bailey, came up with names for the things we often see in comics and cartoons: “briffit” is the dust cloud a character makes when he runs away quickly; “plewds” are the beads of sweat when a character is under duress; and “grawlix” are symbols such as “#@*%” that stand in for curse words. (merriam-webster.com)",
                "48. A mash-up of two words to make a new word (such as breakfast and lunch into brunch, or motel from motor and hotel) is called a portmanteau. In case you’re wondering, the word “portmanteau” itself is not a portmanteau; it’s a compound word that refers to a duel-sided suitcase. (merriam-webster.com) ",
                "49. The dog ate John Steinbeck’s homework—literally. The author’s pup chewed up an early version of Of Mice and Men. “I was pretty mad, but the poor fellow may have been acting critically,” he wrote.",
                "50. Among lost works, this story might be even worse: Ernest Hemingway’s first wife, Hadley, left a suitcase full of the author’s writing on a train. When she went back to get it, it was gone. “I had never seen anyone hurt by a thing other than death or unbearable suffering except Hadley when she told me about the things being gone,” Hemingway wrote in A Moveable Feast.",
                "51. The original title of Jane Austen’s Pride and Prejudice was First Impressions. (jasna.org)",
                "52. Mary Shelley wrote Frankenstein when she 18, during a ghost story competition while staying in Switzerland with writers Percy Shelley (her lover) and Lord Byron. (penguinrandomhouse.com)",
                "53. German chocolate cake doesn’t come from Germany. It was named for a person, Sam German, who created a type of baking chocolate for Baker’s in 1852. (npr.org)",
                "54. Hawaiian pizza was created in Ontario, Canada, by Greek immigrant Sam Panopoulos in 1962. (cbc.ca)",
                "55. Almost all commercially grown artichokes, 99.9 percent, come from California. One town in particular, Castroville, is nicknamed “the Artichoke Capital of the World.” (visitcalifornia.com)",
                "56. The different colors of Froot Loops cereal all taste the same—they’re not individual flavors. (time.com)",
                "57. What’s inside a Kit Kat? Broken Kit Kats that are damaged during production—they get ground up and go between the wafers inside, along with cocoa and sugar. That’s a way to not let anything go to waste! (today.com)",
                "58. Pound cake got its name because the original recipe required a pound each of butter, flour, sugar and eggs. That’s a lot of cake—but it was meant to last for a long time.",
                "59. The difference between jam and jelly is that jam is made with mashed up fruit while jelly is made with fruit juice. (bonapetit.com)",
                "60. Preserves are like jam but made with more whole fruit. Marmalade is preserves made from citrus fruit.",
                "61. Flamin’ Hot Cheetos were developed by a janitor at Frito-Lay, Richard Montanez, who got the idea after putting chili powder on some reject Cheetos and then pitched it to the CEO. He’s now a successful executive and motivational speaker, and a movie is in the works about his life. (cnbc.com)",
                "62. Coca-Cola actually sells soup in a can. Bistrone is a nourishing meal on the go, available in two flavors in Japan. (worldofcoca-cola.com)",
                "63. The biggest pizza ever created was 13,580 square feet, made in Rome, Italy, in 2012. The pizza was gluten-free and named “Ottavia” after a roman emperor. (guinnessworldrecords.com)",
                "64. The tallest building in the world is the Burg Khalifa in Dubai, standing at over 2,700 feet. (skyscrapercenter.com)",
                "65. The tallest building in the US is One World Trade Center in New York, which comes in at number six on the worldwide list. It stands at exactly 1,776 feet as a nod to the date of the Declaration of Independence.",
                "66. The Empire State Building in New York was the tallest building in the world from 1931 until 1971, and was the first building of over 100 floors.",
                "67. Contrary to popular belief, it’s really, really hard to see the Great Wall of China from space, particularly with the naked eye. (nasa.gov)",
                "68. The first footprints on the moon will remain there for a million years. (nasa.gov)",
                "69. Days on Venus are longer than years. Due to its slow axis rotation, it takes 243 Earth days to spin once; but it only takes 225 Earth days to go around the sun. (nasa.gov) ",
                "70. Humans could never “land” on Jupiter, Saturn, Uranus or Neptune because they are made of gas and have no solid surface. (natgeokids.com)",
                "71. But you could ice skate on one of Jupiter’s moons, Europa, which is covered in ice. An Axel jump would take you 22 feet in the air! (nasa.gov)",
                "72. Our modern interpretation of Santa Claus with a red outfit and white beard is due in large part to holiday Coca-Cola ads that began in 1931. (coca-cola.com)",
                "73. Queen Victoria’s husband, Prince Albert, wasn’t the first to introduce Christmas trees to Britain from his native Germany—Queen Charlotte did that in the late 1700s. But, Victoria and Albert are credited with popularizing the custom in the mid-1800s. (royal.uk)",
                "74. Buckingham Palace in London, England, has 775 rooms, including 78 bathrooms. (royal.uk)",
                "75. The White House in Washington, DC, has 132 rooms, including 35 bathrooms. (whitehouse.gov)",
                "76. It takes 570 gallons to paint the exterior of the White House. (whitehouse.gov)",
                "77. The teddy bear is named after President Theodore Roosevelt. After he refused to shoot a captured black bear on a hunt, a stuffed-animal maker decided to create a bear and name it after the president. (nps.gov)",
                "78. Lincoln Logs were created by John Lloyd Wright, son of famous architect Frank Lloyd Wright, in the 1920s. They were named after Abraham Lincoln, who grew up in a log cabin. (nps.gov)",
                "79. Play-Doh started out as a wallpaper cleaner before the head of the struggling company realized the non-toxic material made a good modeling clay for children and rebranded it. (museumofplay.org)",
                "80. In the 1940s, a retired schoolteacher came up with Candyland to entertain children who were hospitalized from polio. Because its color system required no reading, young kids could easily play. (toyhalloffame.org) ",
                "81. People started wearing pajamas, originally spelled “pyjamas,” instead of nightgowns so they’d be prepared to run outside in public during World War I air raids in England. (bbc.co.uk)",
                "82. At Medieval Times dinner attractions, you eat with your hands because people didn’t use utensils in the middle ages. (medievaltimes.com)",
                "83. Freelancers originally referred to self-employed, sword-wielding mercenaries: literally “free lancers.” (merriam-webster.com)",
                "84. We shake hands to show we’re unarmed. (bbc.co.uk)",
                "85. Although no longer connected to the beer company, Guinness World Records was founded by the managing director of Guinness Brewery in the 1950s. (guinnessworldrecords.com).",
                "86. Michelin stars are highly coveted by elite and upscale restaurants the world over—but they’re actually given out by the Michelin tire company, the same one whose mascot is the marshmallow-like Michelin Man. If you want to get fancy, pronounce it in the original French, “mich-LEH.” (michelin.com)",
                "87. More people visit France than any other country (Spain is second; the US third). (e-unwto.org)",
                "88. You can still stay at the world’s oldest hotel, Nisiyama Onsen Keiunkan in Japan, which was founded in 705 AD. (guinnessworldrecord.com)",
                "89. The longest place name in the word, at 85 letters, is “Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu,” New Zealand. Locals just call it Taumata Hill. (newzealand.com)",
                "90. The coldest temperature ever recorded occurred in Antarctica, -144 Fahrenheit, as reported by researchers in a scientific journal in 2018.",
                "91. The hottest temperature ever recorded occurred in Furnace Creek, Death Valley, California, at 134 degrees Fahrenheit on July 10, 1913. (public.wmo.int)",
                "92. Japan records the most earthquakes of any country in the world; but the most earthquakes actually occurs in Indonesia. (usgs.gov)",
                "93. Each year 16 million thunderstorms happen around the world, and at any given moment, there are about 2,000 thunderstorms in progress. (nssl.noaa.gov)",
                "94. Sweden has 267,570 islands, the most of any country in the world.",
                "95. Australia contains a number of pink lakes, but the most stunning is the Pepto Bismol-colored Lake Hillier. The color may be the result of certain algae. (australia.com)",
                "96. At over 29,000 feet tall, Mt. Everest is the highest point on Earth, but it doesn’t compare to the deepest point on Earth, the Mariana Trench, which is over 36,000 feet deep—nearly seven miles—in the Pacific Ocean.",
                "97. This isn’t exactly a “fun” fact, but there are over 200 dead bodies of climbers on Mt. Everest because it’s so difficult to bring them down. (outsideonline.com)",
                "98. Only two people have ever swum the entire length of the 2,350-mile Mississippi River: Slovenian long-distance swimmer Martin Strel in 2002 and American former Navy SEAL Chris Ring in 2015. Strel swam for 68 days in a row; Ring took one day off a week, taking 181 days. (strel-swimming.com)",
                "99. Visitors are not allowed to scatter loved ones’ ashes at Disney World or Disneyland. This is apparently a problem, particularly around the Haunted Mansion attraction. (wsj.com)",
                "100. The man who designed the Pringles can, Fred Bauer, is buried in one—or at least some of his ashes are. (npr.org)",
                "101. There’s a world record for the holder of the most world records: Ashrita Furman, who’s set more than 600 records and currently holds more than 200. His records have ranged from fastest mile on a pogo stick, longest time to hula hoop underwater and greatest distance traveled on a bicycle balancing a milk bottle on the head. (guinnessworldrecords.com)",
            ],
            _question: [
                    "1. Do you think the big toe feels self-conscious about being the “BIG” toe? ",
                    "2. Why do we use leaf-blowers instead of leaf-suckers? ",
                    "3. Why didn’t the 3 Little Piggies build a house underground?",
                    "4. Captain America has a shield, but where’s his sword?",
                    "5. When you eat a gummy bear, do you eat the head or the feet first?",
                    "6. If he had been bitten by a radioactive man, would Spiderman’s name have been Manman?",
                    "7. Do zombies eat brains because they’re hungry for knowledge?",
                    "8. Why is the chicken even crossing the road? Where are its owners?",
                    "9. Do window cleaners get tired of seeing their own reflections all day?",
                    "10. How come solar panels don’t overheat?",
                    "11. If you can cook an egg on really hot concrete, why don’t we make an omelet?",
                    "12. If you could teleport to any bathroom in the world, which one would you choose?",
                    "13. If they’re called chicken wings, where did all the feathers go?",
                    "14. Do car tires get tired?",
                    "15. When tree leaves change color, do they say “new look, who dis?”",
                    "16. Do elves have to use double the q-tips to clean their ears?",
                    "17. Why do they call them pig-tails if pigs only have 1 tail?",
                    "18. What sound does a flute make if you sneeze into it?",
                    "19. If a balloon pops in a vacuum, can you hear it?",
                    "20. If 100 people poked your belly at the same time, would you burst?",
                    "21. What exactly does puppy breath smell like?",
                    "22. If your sibling turned into a dog, would you walk him/her?",
                    "23. If newborns smell good, shouldn’t our smell improve as we age?",
                    "24. If dragons can breathe fire, what happens when they accidentally sneeze?",
                    "25. What do rocks taste like?",
                    "26. If blood tastes metallic, does that mean vampires like to snack on metal?",
                    "27. Why is it called “loose change” if heavier than paper money?",
                    "28. If there’s a rabbit on the moon, where is its carrot?",
                    "29. When someone is sad, we say they’re blue, so if someone is really sad are they dark blue?",
                    "30. Does having stage fright mean you’re afraid of raised wooden platforms?",
                    "31. If the important thing is to get up after falling, why don’t we just learn better balance?",
                    "32. Why are they called headphones if you don’t use them to talk?",
                    "33. If a candle melts and evaporates, does that mean we inhaled an entire candle through our nose?",
                    "34. If bananas have a peel, does that mean we’re skinning it to eat its insides?",
                    "35. When people say someone lost their marbles, why don’t they help look for them?",
                    "36. Do doctors say “ahh” and check their throats when they’re brushing their teeth in the morning?",
                    "37. How do you change the water on a waterbed so it doesn’t grow algae?",
                    "38. If blue is the color of the sky, then what’s the color of the land?",
                    "39. If your refrigerator is still running, is it because it’s trying to lose weight?",
                    "40. Did you remember to turn the stove off? Are you positive?",
                    "41. If hair is dead, why doesn’t it all fall off when the wind blows?",
                    "42. If one twin closes their eyes, does the other twin get scared of the dark?",
                    "43. When you crack your knuckles, is that just the sound of your bones screaming?",
                    "44. What happens to tea bags if you let them sit in water all day?",
                    "45. If you eat a spoonful of ground coffee, do you get more or less caffeine?",
                    "46. If you roll a dice down a mountain, will that give you better odds?",
                    "47. Why do they call it popcorn ceiling? Shouldn’t it be called kernel ceiling?",
                    "48. If grasslands exist, are there also weedlands?",
                    "49. Where do witches go to remove their warts?",
                    "50. Are donut holes just an excuse to eat more donuts?",
                    "51. If sunglasses are for protection, why do they make people look suspicious. ",
                    "52. What would happen if it got hotter instead of colder at night?",
                    "53. If the moon is made of cheese, where are the giant crackers?",
                    "54. If you scream and no sound comes out, is it really a scream?",
                    "55. What if the alphabet started with the letter Z?",
                    "56. When you talk in your sleep, is that your true self trying to come out?",
                    "57. Do dentists just really like making you uncomfortable by asking you questions while you can’t speak?",
                    "58. If we enjoy stepping on puddles, why don’t we step on lakes?",
                    "59. Are tears just built up salt escaping our body?",
                    "60. If you could talk to animals, would you tell them all your secrets?",
                    "61. If you had to change your name to any superhero, which one would you choose?",
                    "62. If you could shapeshift, how often would you impersonate Chris Hemsworth?",
                    "63. If you could name a star, would you choose an animal name or a human name?",
                    "64. Why is it called a pineapple if looks more like a papaya?",
                    "65. Why do we call people a “jack of all trades” but they don’t actually trade?",
                    "66. If they can make a wheel of cheese, can they also make a tire of cheese?",
                    "67. If a mom tells a bad joke, do we call it a mom joke or a dad mom joke?",
                    "68. Who referees the referees?",
                    "69. If you could 3D print food, would you still need to add spices to it?",
                    "70. Are boxers just adult children who were never told hitting is wrong?",
                    "71. Should expecting parents prepare for the baby by setting alarms every 2 hours?",
                    "72. If violin bows are made from horsehair, what would an instrument made from unicorn hair be called?",
                    "73. If a white flag means surrender, does a black flag mean attack?",
                    "74. If he had lived, would Blackbeard have changed his name to Whitebeard when he got old? ",
                    "75. Do high-speed trains run out of breath?",
                    "76. If we can bounce on the moon, why don’t we put a giant bouncy house up there?",
                    "77. Why do people say I got your back if danger usually comes right at your front?",
                    "78. If wine is just grape juice, does that mean beer is wheat juice?",
                    "79. Why is it called a monkey wrench if it’s shaped nothing like a monkey?",
                    "80. Why is it called peanut butter if there is no butter involved?",
                    "81. If plants grow bigger with love, why don’t farmers use that secret to grow enormous vegetables?",
                    "82. When the sun sets is it because it’s shy and hiding away?",
                    "83. If there’s a New Zealand, where did the Old Zealand go?",
                    "84. If all the planets are named after Roman gods, who chose the name Earth?",
                    "85. When your heart breaks, what can you eat to glue it back together?",
                    "86. Why are Pokemon called “pocket monsters” when most of them are too big to actually fit in your pocket?",
                    "87. When people go soul-searching does it mean they’re ghost-hunting?",
                    "88. How can the fruit salad ambrosia be the food of the gods if marshmallows weren’t invented yet?",
                    "89. Were The Beatles named after a specific beetle species or just beetles in general?",
                    "90. When you’re saying goodbye to someone, why do they call it waving if there’s no water involved?",
                    "91. If a butterfly’s wings can cause a hurricane, why don’t we name hurricanes after the butterfly that caused it?",
                    "92. When people say “so long” what are they talking about? The length of their next visit?",
                    "93. If you bite your nails, does it mean you’re just really hungry?",
                    "94. If the pen is mightier than the sword, why didn’t knights carry giant pens around?",
                    "95. Is fog just clouds that got too close to the ground?",
                    "96. What do elephants do if they have an itch in their trunk?",
                    "97. Why don’t flashdrives actually flash?",
                    "98. Why are the X-Men not called X-People since there are also women in the team?",
                    "99. Do spiders really need 8 legs or are they just greedy?",
                    "100. Why do they say “one size fits all” when it clearly doesn’t fit a baby? "
                ],
        },
        // getters for all components, return random component
        get greeting() {
            return this.getRandomPhrase(this._conversationData._greeting);
        },
        get question() {
            return this.getRandomPhrase(this._conversationData._question);
        },
        get fact() {
            return this.getRandomPhrase(this._conversationData._fact);
        },
        get continuation() {
            return this.getRandomPhrase(this._conversationData._continuation);
        },

        // takes in array of phrases and returns random phrase
        getRandomPhrase(phraseArray) {
            return phraseArray[Math.floor(Math.random() * phraseArray.length)];
        }
        
    };

    // game logic
};

main();

